# Generated by Django 5.2 on 2025-04-06 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productvariation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productvariation'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
