# Generated by Django 5.2 on 2025-04-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_advertisement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
